# Generated by Django 4.0.6 on 2022-08-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_account_id_alter_card_id_alter_currency_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_destination', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_origin', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=6),
        ),
    ]
